
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[424] =
    {   0,
        0,    0,   66,   64,   62,   63,   59,   61,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,    0,    0,   59,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,    0,    0,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,

       60,   60,   60,   60,   53,   60,   54,   60,   60,    0,
        0,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   44,   60,   60,   60,   60,   60,   20,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   55,   60,   60,   60,   60,   60,   60,    0,    0,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,    4,   60,   60,   60,   48,   60,   60,   60,   60,

        0,   60,   60,   60,   60,   60,   60,    0,    0,   60,
        3,   23,   60,   60,   60,   24,   57,   60,   60,   60,
       60,   60,   60,   60,   60,   45,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       46,   60,   60,   60,   60,   60,   60,    0,   60,    8,
       60,   60,   47,   60,    0,    0,   60,   60,   60,   60,
       39,   60,   60,   60,   60,   60,   60,   60,   60,    9,
       60,   60,   60,   15,   60,   60,   60,   60,   60,   60,
       60,   60,   10,   60,   60,   60,   60,   60,    0,   60,
       40,   60,   60,    0,    0,   60,   60,   60,   60,   60,

       60,   60,   37,   60,   60,   60,    2,   19,   18,   60,
       17,   60,   16,   60,   42,   11,   60,   60,   60,   60,
       60,   60,   60,   56,   60,   60,   12,    0,    0,   60,
       60,   38,   60,   60,   60,   60,   60,   60,   60,   21,
       60,   60,   60,   60,   60,   60,   52,   60,   60,   60,
       60,   51,    0,    0,   60,   60,   60,   43,   60,    1,
       60,   60,   49,   22,   60,   60,   60,   60,    6,   14,
       60,   25,   60,    0,    1,   60,   60,   60,   28,   60,
       60,   35,   60,   60,   13,   50,   60,    0,   60,   36,
       29,   60,   26,   60,   60,   27,    0,   60,   60,    7,

        5,   58,   41,   60,   60,   60,   58,   58,   30,   31,
       32,   33,   34,   58,   58,   58,   58,   58,   58,   58,
       58,    1,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    5,    1,
        1,    1,    1,    1,    1,    1,    1,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    7,    8,    1,
        1,    1,    1,    1,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   18,   29,   18,   30,   31,
        1,    1,    1,    1,   32,    1,   33,   18,   18,   18,

       34,   18,   35,   36,   37,   18,   18,   38,   39,   18,
       40,   18,   18,   41,   18,   18,   18,   18,   18,   18,
       18,   18,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[43] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1
    } ;

static const flex_int16_t yy_base[427] =
    {   0,
        0,    0,  867,  850,  849,  848,   37,  847,   53,   95,
       28,   25,   23,   41,  839,   29,   44,   55,   54,   50,
       58,   91,   21,   78,  103,   99,  845,   52,   69,  837,
       63,   69,   66,   82,  102,   83,  105,  120,   86,  836,
      119,  117,  113,  126,  125,  132,  127,  130,  131,  134,
      140,  143,  147,  144,  155,  146,  160,  152,  154,  162,
      158,  167,  171,  168,  180,  176,  177,  176,  179,  190,
      185,  182,  187,  184,  188,  198,  193,  196,  195,  211,
      212,  204,  203,  215,  206,  835,  209,  230,  227,  222,
      219,  834,  221,  231,  224,  233,  246,  242,  237,  243,

      245,  244,  240,  262,  833,  253,  832,  252,  268,  262,
      264,  269,  260,  265,  272,  267,  279,  274,  283,  277,
      276,  831,  282,  287,  288,  289,  298,  830,  300,  296,
      306,  301,  303,  308,  310,  309,  319,  315,  313,  318,
      330,  327,  321,  322,  331,  338,  332,  329,  347,  345,
      350,  353,  339,  340,  349,  356,  354,  357,  358,  359,
      358,  360,  371,  362,  368,  370,  377,  373,  378,  375,
      382,  387,  384,  383,  389,  392,  394,  401,  396,  403,
      405,  400,  406,  413,  414,  415,  422,  416,  419,  420,
      423,  829,  425,  426,  435,  828,  429,  442,  827,  445,

      451,  434,  443,  441,  438,  440,  455,  455,  833,  462,
      825,  824,  463,  460,  458,  823,  822,  464,  467,  470,
      469,  471,  475,  472,  481,  821,  479,  478,  482,  485,
      496,  497,  488,  489,  492,  503,  504,  499,  506,  514,
      820,  511,  507,  510,  508,  519,  515,  523,  523,  819,
      528,  525,  818,  526,  527,  539,  533,  540,  545,  548,
      817,  537,  538,  539,  541,  559,  563,  560,  551,  816,
      562,  564,  557,  815,  566,  570,  571,  567,  572,  575,
      580,  578,  814,  577,  583,  587,  582,  592,  592,  600,
      813,  594,  599,  600,  602,  598,  604,  606,  609,  615,

      618,  621,  812,  612,  622,  625,  811,  810,  809,  624,
      808,  617,  807,  626,  597,  806,  639,  636,  633,  641,
      635,  638,  644,  812,  645,  653,  804,  639,  656,  658,
      647,  803,  660,  664,  659,  662,  656,  669,  663,  802,
      676,  678,  679,  670,  677,  682,  801,  683,  680,  694,
      693,  800,  693,  694,  700,  699,  695,  799,  702,  798,
      704,  705,  797,  796,  696,  706,  711,  719,  795,  794,
      721,  793,  717,  721,  799,  716,  722,  725,  791,  728,
      733,  790,  741,  743,  789,  788,  740,  725,  735,  787,
      785,  736,  784,  742,  746,  782,  738,  747,  762,  781,

      779,  785,  777,  763,  764,  775,  764,  760,  756,  738,
      737,  690,  457,  766,  762,  772,  388,  779,  777,  781,
      780,  271,  868,  130,  111,   89
    } ;

static const flex_int16_t yy_def[427] =
    {   0,
      423,    1,  423,  424,  424,  424,  424,  424,  425,  425,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,  424,  424,  424,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,  424,  424,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,

       10,   10,   10,   10,   10,   10,   10,   10,   10,  424,
      424,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,  424,  424,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,

      424,   10,   10,   10,   10,   10,   10,  424,  424,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,  424,   10,   10,
       10,   10,   10,   10,  424,  424,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,  424,   10,
       10,   10,   10,  424,  424,   10,   10,   10,   10,   10,

       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,  424,   10,   10,   10,  424,  424,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,  424,  424,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,  424,  424,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,  424,   10,   10,
       10,   10,   10,   10,   10,   10,  424,   10,   10,   10,

       10,  426,   10,   10,   10,   10,  426,  426,   10,   10,
       10,   10,   10,  426,  426,  426,  426,  426,  426,  426,
      426,  426,    0,  423,  423,  423
    } ;

static const flex_int16_t yy_nxt[911] =
    {   0,
        4,    5,    6,    5,    4,    7,    4,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   15,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,    4,   29,   30,   34,   30,   38,   30,   55,   35,
       30,   30,   28,   27,   27,   27,   27,   36,   40,   27,
       27,   37,   39,   30,   41,   43,   30,   28,   31,   42,
       46,   44,   30,   32,   29,   47,   30,   30,   48,   45,
       30,   67,   49,   68,   28,   30,   56,   69,   30,  407,
       57,   30,   40,   73,   27,   27,   27,   27,   27,   50,

       30,   27,   27,   51,   30,   30,   70,   78,   30,   58,
       31,   30,   52,   30,   64,   53,   54,   33,   59,   60,
       71,   30,   72,   65,   30,   30,   61,   30,   75,   80,
       27,   76,   62,   85,   63,   30,   27,   74,   82,   30,
       66,   30,   30,   86,   83,   81,   84,   30,   30,   30,
       87,   77,   30,   30,   30,   95,   30,   89,   90,   94,
       91,   88,   30,   97,   92,   30,   30,   96,   30,   30,
       99,   93,   98,  100,   30,  102,   30,   30,  101,  106,
       30,  103,   30,   40,   30,  104,  105,  107,  108,   30,
       30,   28,   28,   30,  112,  113,  109,   40,   30,  111,

      114,   30,   30,  115,   30,  117,   30,   30,  119,   30,
       30,  110,   30,  116,  120,   30,  123,   30,   30,  121,
       30,  118,  122,  124,  125,   30,   30,  128,   30,  127,
      140,   30,  129,   30,   30,  126,  131,   30,  132,  133,
      134,   30,  139,   30,   30,  141,   30,  143,  135,   30,
      145,  144,  136,   30,  137,   30,  138,  147,  148,   30,
      146,  150,   30,  149,   30,   30,   30,   30,   30,  151,
      154,  153,  152,  155,  156,   30,  158,   28,  157,   28,
      162,  161,   30,  163,   30,  160,  408,   30,  165,   30,
       30,   30,  164,  166,   30,  167,   30,  169,   30,   30,

      171,   30,  170,  159,   30,   30,  176,  173,  172,   30,
       30,   30,  174,  168,  179,  175,  177,  178,   30,  180,
       30,  181,   30,   30,  182,   30,  183,  184,   30,  185,
       30,   30,   30,  186,  187,   30,  188,   30,  189,  190,
       30,   30,   40,   30,   30,  191,  194,  193,  192,   30,
      196,   30,   30,   30,   30,  197,  195,  198,  199,  201,
       30,   30,   30,  204,  203,  202,  200,   30,  205,   30,
      206,   30,   30,   28,   28,   30,   30,  207,   30,   30,
       30,  213,   30,  212,   30,  209,  211,  216,  214,  210,
       30,  208,   30,   30,  215,   30,  218,   30,  220,   30,

       30,  219,  221,  418,   30,   30,   30,  217,  223,   30,
      222,   30,  225,  224,   30,  226,   30,  227,   30,  229,
      228,  230,   30,   30,  231,   30,  232,   30,   30,  233,
      234,  235,  236,  238,  237,   30,   30,   30,   30,  240,
      239,   30,   30,  243,   30,   30,  241,   30,   30,  244,
      242,   30,  245,  247,  248,  250,   30,   30,  249,  251,
       30,  253,   30,   30,   30,   30,   28,   30,  252,  254,
       28,  257,  259,  258,  260,  262,  261,   30,  263,   30,
       30,  264,   30,  265,   30,   30,   30,  266,  267,   30,
      270,   30,   30,   30,   30,  268,  255,   30,   40,  269,

       30,   30,  271,   30,   30,  272,  273,   30,  275,  274,
       30,   30,  277,  276,   30,  278,  279,  281,   30,   30,
      280,   30,  282,  283,  285,   30,   30,  284,   30,   30,
       30,  287,   30,   30,  286,  288,   30,   30,   28,  290,
      291,   30,   28,  289,  293,   30,  292,   30,   30,  296,
       30,  295,  297,  298,   28,   30,  299,  300,  301,   30,
       30,   30,   30,   30,  302,  303,  294,   30,   67,  304,
       30,  305,  306,   30,  308,  310,  309,  307,  311,   30,
      312,   30,   30,  313,   30,   30,   30,  314,   30,   30,
      315,  319,   30,   30,   30,  316,  317,   30,  318,   30,

       30,  320,   30,  321,   30,   30,  323,   28,  325,   30,
      326,  327,  322,  324,   30,   28,   30,   28,  343,   30,
       30,   30,   30,  330,  331,  334,   30,  329,   30,  333,
      332,   30,  335,  336,   30,  341,  340,   30,  337,   30,
       30,  328,  338,   30,   30,  339,   30,   30,   30,  344,
      345,  346,  342,  347,   28,   30,  348,   30,   30,  349,
       30,   30,  350,   30,  352,  351,   30,   30,  354,   30,
      355,   28,  361,  356,  357,   30,  358,  359,   30,  353,
       30,   30,   30,  362,   30,   30,   30,  360,  364,  363,
      365,   30,   30,  366,  369,  368,  371,  367,   30,   30,

       30,   30,   30,  370,   30,   30,  372,  373,   28,   28,
      376,  377,   30,  378,  379,   30,   30,   30,   30,  375,
      382,   30,   30,  381,   30,  380,   30,   30,   30,  384,
      383,  385,  386,   30,  374,  387,   28,  391,   30,   30,
       28,   30,  389,   30,   30,  393,  390,   30,  392,  394,
       30,  395,  396,   28,  388,   30,  398,   30,   30,   30,
       30,  400,   30,   30,   30,   30,  397,  399,   30,   30,
      401,  403,  404,  409,  410,  408,  402,  408,   30,  408,
      405,  408,  411,  416,  406,   30,   30,  408,  415,  414,
      412,  419,  408,  421,  408,  408,  408,  413,  417,   30,

      408,   30,  420,   30,   30,  422,   30,   30,  414,   30,
       30,   30,   30,   30,   28,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   28,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,
       30,   30,   30,   30,   30,   30,   30,   30,  256,  246,
       30,   30,   30,   30,   30,   30,  142,  130,   79,   30,
       28,   30,   28,   28,   28,   28,  423,    3,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,

      423,  423,  423,  423,  423,  423,  423,  423,  423,  423
    } ;

static const flex_int16_t yy_chk[911] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    7,   23,   11,   13,   13,   12,   23,   11,
       11,   16,    7,    9,    9,    9,    9,   11,   16,    9,
        9,   12,   14,   14,   17,   18,   17,   28,    9,   17,
       19,   18,   20,    9,   29,   20,   19,   18,   21,   18,
       21,   28,   21,   32,   29,   31,   24,   33,   33,  426,
       24,   32,   31,   36,    9,   10,   10,   10,   10,   22,

       24,   10,   10,   22,   34,   36,   34,   39,   39,   24,
       10,  425,   22,   22,   26,   22,   22,   10,   25,   25,
       35,   26,   35,   26,   35,   25,   25,   37,   38,   41,
      424,   38,   25,   45,   25,   43,   10,   37,   42,   42,
       26,   41,   38,   46,   43,   41,   44,   45,   44,   47,
       47,   38,   48,   49,   46,   53,   50,   49,   50,   52,
       51,   48,   51,   55,   51,   52,   54,   54,   56,   53,
       57,   51,   56,   57,   58,   59,   59,   55,   58,   63,
       61,   60,   57,   59,   60,   61,   62,   64,   65,   62,
       64,   66,   67,   63,   68,   69,   65,   64,   68,   67,

       70,   69,   65,   71,   72,   73,   74,   71,   75,   73,
       75,   66,   70,   72,   76,   77,   79,   79,   78,   77,
       76,   74,   78,   80,   81,   83,   82,   84,   85,   83,
       90,   87,   85,   80,   81,   82,   87,   84,   88,   88,
       88,   91,   89,   93,   90,   91,   95,   93,   88,   89,
       95,   94,   88,   94,   88,   96,   88,   97,   98,   99,
       96,  100,  103,   99,   98,  100,  102,  101,   97,  101,
      104,  103,  102,  106,  108,  106,  109,  110,  108,  111,
      113,  112,  113,  114,  104,  111,  422,  114,  115,  116,
      109,  112,  114,  116,  115,  117,  118,  119,  121,  120,

      121,  117,  120,  110,  123,  119,  127,  124,  123,  124,
      125,  126,  125,  118,  131,  126,  129,  130,  130,  132,
      127,  133,  129,  132,  134,  133,  135,  136,  131,  137,
      134,  136,  135,  138,  139,  139,  140,  138,  141,  142,
      140,  137,  139,  143,  144,  143,  146,  145,  144,  142,
      148,  148,  141,  145,  147,  149,  147,  150,  151,  152,
      146,  153,  154,  155,  154,  153,  151,  150,  156,  149,
      157,  155,  151,  159,  160,  152,  157,  158,  156,  158,
      161,  164,  162,  163,  164,  160,  162,  167,  165,  161,
      165,  159,  166,  163,  166,  168,  169,  170,  171,  167,

      169,  170,  172,  417,  171,  174,  173,  168,  174,  172,
      173,  175,  176,  175,  176,  177,  177,  178,  179,  180,
      179,  181,  182,  178,  182,  180,  183,  181,  183,  184,
      185,  186,  187,  189,  188,  184,  185,  186,  188,  191,
      190,  189,  190,  195,  187,  191,  193,  193,  194,  197,
      194,  197,  198,  200,  201,  203,  202,  195,  202,  204,
      205,  206,  206,  204,  198,  203,  201,  200,  205,  207,
      208,  210,  214,  213,  215,  219,  218,  207,  220,  413,
      215,  221,  214,  222,  210,  213,  218,  223,  224,  219,
      228,  221,  220,  222,  224,  225,  208,  223,  221,  227,

      228,  227,  229,  225,  229,  230,  231,  230,  233,  232,
      233,  234,  235,  234,  235,  236,  237,  239,  231,  232,
      238,  238,  240,  242,  244,  236,  237,  243,  239,  243,
      245,  246,  244,  242,  245,  247,  240,  247,  248,  249,
      251,  246,  255,  248,  254,  249,  252,  252,  254,  257,
      251,  256,  258,  259,  256,  257,  260,  262,  263,  262,
      263,  264,  258,  265,  264,  265,  255,  259,  256,  266,
      260,  267,  268,  269,  271,  273,  272,  269,  275,  273,
      276,  266,  268,  277,  271,  267,  272,  278,  275,  278,
      279,  284,  276,  277,  279,  280,  281,  280,  282,  284,

      282,  285,  281,  286,  287,  285,  288,  289,  290,  286,
      292,  293,  287,  289,  288,  294,  292,  295,  315,  315,
      296,  293,  290,  296,  297,  300,  297,  295,  298,  299,
      298,  299,  301,  302,  304,  312,  310,  300,  304,  312,
      301,  294,  305,  302,  305,  306,  310,  306,  314,  317,
      318,  319,  314,  320,  328,  319,  321,  321,  318,  322,
      322,  317,  323,  320,  326,  325,  323,  325,  329,  331,
      330,  329,  337,  331,  333,  326,  334,  335,  337,  328,
      330,  335,  333,  338,  336,  339,  334,  336,  341,  339,
      342,  338,  344,  343,  346,  345,  349,  344,  341,  345,

      342,  343,  349,  348,  346,  348,  350,  351,  353,  354,
      355,  356,  412,  357,  359,  351,  350,  357,  365,  354,
      365,  356,  355,  362,  359,  361,  361,  362,  366,  367,
      366,  368,  371,  367,  353,  373,  374,  378,  376,  373,
      388,  368,  376,  371,  377,  381,  377,  378,  380,  383,
      380,  384,  387,  397,  374,  381,  389,  389,  392,  411,
      410,  394,  387,  383,  394,  384,  388,  392,  395,  398,
      395,  398,  399,  404,  405,  408,  397,  415,  409,  407,
      399,  414,  405,  415,  399,  404,  405,  416,  414,  408,
      405,  418,  419,  420,  418,  421,  420,  406,  416,  403,

      402,  401,  419,  400,  396,  421,  393,  391,  418,  390,
      386,  385,  382,  379,  375,  372,  370,  369,  364,  363,
      360,  358,  352,  347,  340,  332,  327,  324,  316,  313,
      311,  309,  308,  307,  303,  291,  283,  274,  270,  261,
      253,  250,  241,  226,  217,  216,  212,  211,  209,  199,
      196,  192,  128,  122,  107,  105,   92,   86,   40,   30,
       27,   15,    8,    6,    5,    4,    3,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,
      423,  423,  423,  423,  423,  423,  423,  423,  423,  423,

      423,  423,  423,  423,  423,  423,  423,  423,  423,  423
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "filterJGEXtoFOF.l"
#line 2 "filterJGEXtoFOF.l"

#include "filterJGEXtoFOF.tab.h"
#line 784 "lex.yy.c"
#line 785 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 11 "filterJGEXtoFOF.l"


#line 1005 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 424 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 868 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 13 "filterJGEXtoFOF.l"
{ /* delete everything up to HYPOTHESES */ }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 14 "filterJGEXtoFOF.l"
{ return(MIDPOINT); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 15 "filterJGEXtoFOF.l"
{ return(POINT); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 16 "filterJGEXtoFOF.l"
{ return(POINT); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 17 "filterJGEXtoFOF.l"
{ return(PERPENDICULAR); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 18 "filterJGEXtoFOF.l"
{ return(QUADRANGLE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 19 "filterJGEXtoFOF.l"
{ return(PARALLELOGRAM); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 20 "filterJGEXtoFOF.l"
{ return(SQUARE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 21 "filterJGEXtoFOF.l"
{ return(NSQUARE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 22 "filterJGEXtoFOF.l"
{ return(PSQUARE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 23 "filterJGEXtoFOF.l"
{ return(PENTAGON); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 24 "filterJGEXtoFOF.l"
{ return(TRIANGLE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 25 "filterJGEXtoFOF.l"
{ return(PETRIANGLE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 26 "filterJGEXtoFOF.l"
{ return(REFLECTION); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 27 "filterJGEXtoFOF.l"
{ return(ONLINE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 28 "filterJGEXtoFOF.l"
{ return(ONTLINE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 29 "filterJGEXtoFOF.l"
{ return(ONPLINE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 30 "filterJGEXtoFOF.l"
{ return(ONBLINE); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 31 "filterJGEXtoFOF.l"
{ return(ONALINE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 32 "filterJGEXtoFOF.l"
{ return(LINE); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 33 "filterJGEXtoFOF.l"
{ return(ONCIRCLE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 34 "filterJGEXtoFOF.l"
{ return(ONRCIRCLE); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 35 "filterJGEXtoFOF.l"
{ return(CIRCLE); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 36 "filterJGEXtoFOF.l"
{ return(CYCLIC); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 37 "filterJGEXtoFOF.l"
{ return(RTRIANGLE); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 38 "filterJGEXtoFOF.l"
{ return(ISOTRIANGLE); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 39 "filterJGEXtoFOF.l"
{ return(SIMTRIANGLE); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 40 "filterJGEXtoFOF.l"
{ return(EQTRIANGLE); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 41 "filterJGEXtoFOF.l"
{ return(CONTRIANGLE); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 42 "filterJGEXtoFOF.l"
{ return(INTERSECTIONCC); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 43 "filterJGEXtoFOF.l"
{ return(INTERSECTIONLC); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 44 "filterJGEXtoFOF.l"
{ return(INTERSECTIONLL); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 45 "filterJGEXtoFOF.l"
{ return(INTERSECTIONLT); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 46 "filterJGEXtoFOF.l"
{ return(INTERSECTIONPP); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 47 "filterJGEXtoFOF.l"
{ return(ORTHOCENTER); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 48 "filterJGEXtoFOF.l"
{ return(CIRCUMCENTER); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 49 "filterJGEXtoFOF.l"
{ return(INCENTER); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 50 "filterJGEXtoFOF.l"
{ return(COLLINEAR); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 51 "filterJGEXtoFOF.l"
{ return(EQANGLE); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 52 "filterJGEXtoFOF.l"
{ return(SANGLE); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 53 "filterJGEXtoFOF.l"
{ return(ANGLEBISECTOR); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 54 "filterJGEXtoFOF.l"
{ return(PARALLEL); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 55 "filterJGEXtoFOF.l"
{ return(EQDISTANCE); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 56 "filterJGEXtoFOF.l"
{ return(FOOT); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 57 "filterJGEXtoFOF.l"
{ return(LRATIO); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 58 "filterJGEXtoFOF.l"
{ return(PRATIO); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 59 "filterJGEXtoFOF.l"
{ return(TRATIO); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 60 "filterJGEXtoFOF.l"
{ return(RATIO); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 61 "filterJGEXtoFOF.l"
{ return(LCTANGENT); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 62 "filterJGEXtoFOF.l"
{ return(RTRAPEZOID); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 63 "filterJGEXtoFOF.l"
{ return(TRAPEZOID); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 64 "filterJGEXtoFOF.l"
{ return(RECTANGLE); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 65 "filterJGEXtoFOF.l"
{ return(SYM); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 66 "filterJGEXtoFOF.l"
{ /* Ignora */ }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 67 "filterJGEXtoFOF.l"
{ return(SHOW); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 68 "filterJGEXtoFOF.l"
{ return(NOSHOW); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 69 "filterJGEXtoFOF.l"
{ /* Ignora */ }
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 70 "filterJGEXtoFOF.l"
{ return(FINALIZA); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 72 "filterJGEXtoFOF.l"
{ 
                 yylval.number=atoi(yytext);
                 return(NUMERO); 
               }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 76 "filterJGEXtoFOF.l"
{
                 yylval.string=strdup(yytext);
                 return(VARIABLE);
               }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 80 "filterJGEXtoFOF.l"
{ return(SEPARADOR); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 81 "filterJGEXtoFOF.l"
{ /* skip white spaces */ }
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 82 "filterJGEXtoFOF.l"
{ /*printf("%s",yytext);*/ } 
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 83 "filterJGEXtoFOF.l"
{ /* skip everything else */ }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 84 "filterJGEXtoFOF.l"
ECHO;
	YY_BREAK
#line 1396 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 42);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 424 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 42;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 424 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 423);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 84 "filterJGEXtoFOF.l"



